### ISSUE TITLE
Problem with Essential Custom Fields for JIRA - Last comment and XML export

### ISSUE THREAD

**Issue by ArielAr** [codelabexpert/ecf-issues#1]
Hi,
We recently installed Essential Custom Fields for JIRA plugin in our instance, but we started having problems when we tried to export issues in an XML file. After doing some tests, we realized that the problem was present when any XML unsupported character was present in the 'Last Comment' field. 
Changing the configuration and render options won't help at all. 
We are running a large JIRA instance and this is a blocker for us since we do not have any workaround but to add a plain text line as the last comment. 
Are you aware of this issue? Do you know if there is any fix for this problem? 
I would appreciate much your input about this!
Thanks and regards,
                                   Ariel Arroyo

**Comment by codelabexpert** [comment]
Do you have any examples for invalid characters concerning your issue?

**Comment by ArielAr** [comment]
Hi,
Thanks for taking care of this. Your feedback is much appreciated.
Regarding your question, we have managed to figure out only two problematic characters, this ones are: '&' and '<' only. 
Is there a way to fix this issue besides escaping these special characters? 
Thanks again and best regards,
                                                   Ariel Arroyo

**Comment by codelabexpert** [comment]
Hi,
thanks again for your feedback.
We are evaluating an optional filter escaping this special characters in xml export. Can you give us more information about the problems exporting your issues?

**Comment by codelabexpert** [comment]
Hi,
thank for reporting this bug.
We released a bug fix version 2.2.2 now.

Best regards!

**Comment by ArielAr** [comment]
Hi,
Awesome work!
Thanks so much for so quick response, it is much appreciated.
Best regards,
                     Ariel Arroyo
